name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v7
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v2

    - name: Check formatting
      run: cargo fmt --all --check

    - name: Lint workspace
      run: cargo clippy --workspace --benches --tests --examples -- --deny warnings

    - name: Lint workspace (no default features)
      run: cargo clippy --workspace --benches --tests --examples --no-default-features -- --deny warnings

    - name: Lint workspace (alloc only)
      run: cargo clippy --workspace --benches --tests --examples --no-default-features --features alloc -- --deny warnings

    - name: Lint workspace (derive only)
      run: cargo clippy --workspace --benches --tests --examples --no-default-features --features derive -- --deny warnings

  #allocator-api:
  #  runs-on: ubuntu-latest
  #  timeout-minutes: 5

  #  steps:
  #  - uses: actions/checkout@v7
  #  - uses: dtolnay/rust-toolchain@nightly
  #    with:
  #      components: clippy
  #  - uses: Swatinem/rust-cache@v2
  #    with:
  #      key: allocator-api

  #  - name: Lint workspace
  #    run: cargo +nightly clippy --workspace --benches --tests --examples --features allocator-api -- --deny warnings --allow unused-features

  #  - name: Lint workspace (alloc only)
  #    run: cargo +nightly clippy --workspace --benches --tests --examples --no-default-features --features allocator-api,alloc -- --deny warnings --allow unused-features

  #  - name: Lint workspace (derive only)
  #    run: cargo +nightly clippy --workspace --benches --tests --examples --no-default-features --features allocator-api,derive -- --deny warnings --allow unused-features

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v7
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        key: test-${{ matrix.os }}

    - name: Run Tests
      run: cargo test --workspace

  wasm-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1
      - uses: Swatinem/rust-cache@v2

      - name: Install wasmtime
        run: |
          curl -fsSL https://wasmtime.dev/install.sh | bash
          echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH

      - name: Run Tests (WASIp1)
        run: cargo test --workspace --target wasm32-wasip1
